### ISSUE TITLE
Cant write anything in terminal

### ISSUE THREAD

**Issue by finoghentov** [dongsuo/vue-terminal#14]
![image](https://user-images.githubusercontent.com/45954128/78131949-8fe4c280-7424-11ea-9f4e-153f8283a15a.png)

**Comment by finoghentov** [comment]
Please, can you provide full documantion. You have interesting product but because lack of documentation it's very hard to deal with it

**Comment by dongsuo** [comment]
Sorry for the documentation thing, I will consider your advice. About your problem, can you provide a repo to reproduce?

**Comment by finoghentov** [comment]
> Sorry for the documentation thing, I will consider your advice. About your problem, can you provide a repo to reproduce?

I solve the problem. I took example from demo and research it. I'm not master in js, but as far as I understood the problem was that I didn't resolve promise from start of terminal. So terminal wait for it and didn't become an active. So input was disabled and loading was running but it is Ok now. I think that your module is very usefull. Thank you, I hope you will develop it and please, make good documentation, I waste 3-4 hours to understand how it works. Good luck
