### ISSUE TITLE
How can I start text from new line in terminal?

### ISSUE THREAD

**Issue by finoghentov** [dongsuo/vue-terminal#16]
![image](https://user-images.githubusercontent.com/45954128/78253007-64350b80-74fc-11ea-868f-642719e6198e.png)

Here is my html. This is the answer from composer which starting from new line with \n
I tried to replace \n to a lot of stuff but no result. 
That's how it looks in terminal

![image](https://user-images.githubusercontent.com/45954128/78253087-8595f780-74fc-11ea-9953-40aa6177535f.png)

**Comment by finoghentov** [comment]
Can you make 
![image](https://user-images.githubusercontent.com/45954128/78269080-c3514b00-7511-11ea-98f0-60038f76686a.png)

Instead of 

![image](https://user-images.githubusercontent.com/45954128/78269111-cc421c80-7511-11ea-9054-dbd419a12e30.png)
 Or it affect on something?

**Comment by dongsuo** [comment]
Thanks, I will fix this problem tomorrow.

**Comment by dongsuo** [comment]
https://github.com/dongsuo/vue-terminal/pull/17

Fixed in version 1.2.0.
