### ISSUE TITLE
Vue instace 

### ISSUE THREAD

**Issue by IgorMCHC** [dongsuo/vue-terminal#3]
![image](https://user-images.githubusercontent.com/7894896/57563596-19575600-7376-11e9-9872-8f6b55bed1d2.png)

how do I access a date within the command?

**Comment by dongsuo** [comment]
You can add a time property in task obj, like this:
`pushToList({ time: 'Date Managed By Yourself', type: 'info', label: 'Info', message: 'Terminal Initializing ............' })`.
Is this what you want?

**Comment by IgorMCHC** [comment]
No, I wanted to have access to the instance of vue so I could expand my terminal ... thus simulating a real terminal

**Comment by dongsuo** [comment]
OK, I understand your need, but I can't understand why you need this. Can you explain the reason?

**Comment by dongsuo** [comment]
@IgorMCHC You can describe a scenario where Vue instance is needed.

**Comment by IgorMCHC** [comment]
> @IgorMCHC Você pode descrever um cenário em que a instância do Vue é necessária.

Should I be manipulating some instance date or having to call the Vue store

**Comment by dongsuo** [comment]
Do you mean instance data by 'instance date'?  I think your can manage vue store and instance data outside your termianl component.

**Comment by IgorMCHC** [comment]
But for example, I wanted to make an authentication system using the terminal and inside it access the dates and store the vue when executing a command

**Comment by dongsuo** [comment]
OK, I will consider your need.

**Comment by finoghentov** [comment]
> No, I wanted to have access to the instance of vue so I could expand my terminal ... thus simulating a real terminal

I think that you can solve it adding additional parameter to your command

![image](https://user-images.githubusercontent.com/45954128/78252343-5df25f80-74fb-11ea-843b-65c3529099bc.png)

If I correctly understood you, this example will help you. You adding additional parameter to your object and assign it "this" context which is your component context. And you will have access to your component parameters in your object,
