### ISSUE TITLE
请问我传递属性是这样写没错吗，但是没起效

### ISSUE THREAD

**Issue by qq690712575** [dongsuo/vue-terminal#6]
<vue-terminal :task-list="taskList" :command-list="commandList" style="width:100%;height:100%;margin:0 auto"
                      :title="`深信Aiy计算机协会`"
                      :showHeader="false"
                      greeting="欢迎使用"
                      prompt="aaa"
        ></vue-terminal>
![image](https://user-images.githubusercontent.com/17699491/73333799-e3605600-42a5-11ea-916e-d4d0407b5283.png)

**Comment by dongsuo** [comment]
Sorry, 回复晚了，问题解决了吗？

**Comment by dongsuo** [comment]
已修复

**Comment by qq690712575** [comment]
我已经撤销了这个组件的使用了，修复就好，下次加入

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 东索 <notifications@github.com>
发送时间: Tuesday, March 3, 2020 1:12:38 PM
收件人: dongsuo/vue-terminal <vue-terminal@noreply.github.com>
抄送: Jianle Chen <q690712575@live.com>; Author <author@noreply.github.com>
主题: Re: [dongsuo/vue-terminal] 请问我传递属性是这样写没错吗，但是没起效 (#6)


Sorry, 回复晚了，问题解决了吗？

―
